### ISSUE TITLE
Incompatibility with matlab 2017b

### ISSUE THREAD

**Issue by Davo-Exp4** [stereolabs/zed-matlab#10]
Cordial greetings, you can not compile MEX files, the following errors arise:
CMake Warning (dev) at CMakeLists.txt:16 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Matlab_ROOT is set to:

    C:\Program Files\MATLAB\R2017b

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

I would appreciate your help. Thank you.

**Comment by P-yver** [comment]
Hi, can you look on [this comment](https://github.com/stereolabs/zed-matlab/issues/11#issuecomment-504325507) it may help you.
