### ISSUE TITLE
generate errors

### ISSUE THREAD

**Issue by chunxuli90** [stereolabs/zed-matlab#15]
Hi there,

I got errors when i was generating the project using CMake-GUI,:

CMake Error at mex/CMakeLists.txt:11 (add_library):
  Target "mexZED" links to item " C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v10.0/lib/x64/nppicom.lib" which has leading or trailing
  whitespace.  This is now an error according to policy CMP0004.

And when I built the mex in Visual studio 2017, I got errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z) referenced in function mexFunction	mexZED	C:\Users\Baxter\Documents\MATLAB\zed-matlab\build\mex\mexZED.obj	1	

Whether they are related? Could you please help to give me some suggestions for fixing?

Thank you for your time!

Many thanks

**Comment by P-yver** [comment]
Hi,
The first issue is CUDA related, normally it is simply considered as a warning and does not prevent from building the project.

The second issues is opencv related, we provide binaries in the folder:
_C:\Program Files (x86)\ZED SDK\dependencies\opencv_3.1.0_ 
You can still use your own library if you want, be sure that cmake finds it.
