### ISSUE TITLE
how to compatibility with matlab 2019b on linux 

### ISSUE THREAD

**Issue by hzm2016** [stereolabs/zed-matlab#16]

**Comment by P-yver** [comment]
Hi,
Have you tried our build [instructions](https://github.com/stereolabs/zed-matlab#build-for-linux)?

**Comment by fabianmpa** [comment]
Hi, i am having the same problem. I've already tried the build instructions. Mine is a Zed Mini and i have installed SDK 3.0.

**Comment by P-yver** [comment]
Hi,
can you share the errors you have?
Does came from the CMake or from the project build?

**Comment by fabianmpa** [comment]
They come when i try to run .m scripts on matlab 
For example, if i run the ZED_Camera.m i get this error:


========= ZED SDK PLUGIN =========
-- Retrieve Images and Depth --
Invalid MEX-file '/home/fabian/zed/zed-matlab-master/matlab/mexZED.mexa64':
/home/fabian/zed/zed-matlab-master/matlab/mexZED.mexa64: undefined symbol:
_ZN2cv3Mat20updateContinuityFlagEv

Error in ZED_Camera (line 17)
result = mexZED('open', InitParameters);

**Comment by fabianmpa** [comment]
Update: Works fine wih SDK 3.1
