### ISSUE TITLE
Velocity Tracking on Matlab?

### ISSUE THREAD

**Issue by Helaly96** [stereolabs/zed-matlab#18]
when use the object detection module , I noticed only (iD,label,tracking state,position,boundingbox 2D,bounding box 3d) but not the velocity like the python or C++ version.
is this an issue or it's just not mentioned in the documentation

**Comment by P-yver** [comment]
Hi,
It was missing from the wrapper, it has been added in e88da18bc2a3d4ec7e82d2f0484e0358fb78d632.

**Comment by Helaly96** [comment]
Thank you so much
