### ISSUE TITLE
how to build mexZED and INSTALL

### ISSUE THREAD

**Issue by Expelliarmu** [stereolabs/zed-matlab#20]
Hello,

I don't know what 'Build mexZED' and 'Build INSTALL' mean, and I don't know what to do next. Does anyone have detailed tutorial?

Thanks!

**Comment by P-yver** [comment]
To build from visual studio, press 'F7' or right-click on 'mexZED' in the Solution Explorer view and click on 'Build', then right-click on 'INSTALL' and then on 'build'.

**Comment by Expelliarmu** [comment]
> 
> 
> To build from visual studio, press 'F7' or right-click on 'mexZED' in the Solution Explorer view and click on 'Build', then right-click on 'INSTALL' and then on 'build'.

I see, thank you!
