### ISSUE TITLE
Cmake not finding matlab

### ISSUE THREAD

**Issue by Jordan-Letchford** [stereolabs/zed-matlab#23]
Hi 

I am trying to compile ZED and matlab (2021a version) together through Cmake following the 'Using the ZED SDK' guide and am getting errors. This is on a windows 10, x64 system with CUDA installed and the camera works fine through ZEDexplorer.

I have matlab installed on a different harddrive than my C and have updated my MATLAB_ROOT to reflect this however CMake still can not find it. I then went and manually pointed to the libraries (i hope the right ones) and it compiled but I got errors, the one below (i know its a warning but I can not continue to the next step as that has errors):

WARNING: Target "mexZED" requests linking to directory "G:\Matlab\extern\lib\win64\microsoft".  Targets may link only to libraries.  CMake is dropping the item.

Below is a screen shot. My questions are:

1. are those the correct folders for the libraries I want? can someone confirm? 
2. why can it not find matlab using that MATLAB_ROOT, it is there.
3. How do I solve this warning - I tried to continue to visual studios and build MEXZED and install but that didn't work

![Capture](https://user-images.githubusercontent.com/30902955/115940703-dbfa1d80-a4e5-11eb-9c2b-c90ef3850cb3.JPG)

**Comment by P-yver** [comment]
Hi,
Here is the linked library, can you try with the full path of the file: 

![image](https://user-images.githubusercontent.com/17572319/116214583-21695580-a747-11eb-93eb-801e32b657fe.png)
