### ISSUE TITLE
WARNING: FPS is too low to enable positional tracking and spatial mapping. Consider using PERFORMANCE parameters

### ISSUE THREAD

**Issue by sophie-shin** [stereolabs/zed-matlab#8]
I got this messages from the command window.

```
=========SL_ZED_WITH_MATLAB -- Point Cloud=========
ZED (Init) >> Depth mode: PERFORMANCE
ZED (Init) >> Video mode: HD720@60

result =

    'SUCCESS'


image_size =

        1280
         720

ZED (Init) >> WARNING: FPS is too low to enable positional tracking and spatial mapping. Consider using PERFORMANCE parameters
ZED (Init) >> WARNING: FPS is too low to enable positional tracking and spatial mapping. Consider using PERFORMANCE parameters

```

Any codes were not changed from the original code.
Zedfu works well.

Please help!

**Comment by willshw** [comment]
I'm experiencing this too. My ZED camera is connected to Jetson TX2. Even without rviz open, rostopic hz will show the /point_cloud/cloud_registered was publishing about 10Hz. Did you find the solution?

**Comment by willshw** [comment]
nvm, I think the new package update fixed the issue.

> I'm experiencing this too. My ZED camera is connected to Jetson TX2. Even without rviz open, rostopic hz will show the /point_cloud/cloud_registered was publishing about 10Hz. Did you find the solution?
