### ISSUE TITLE
mexZED('record')

### ISSUE THREAD

**Issue by guidomaiello** [stereolabs/zed-matlab#9]
Hello, 
I'm trying to get Matlab to record videos in the Stereolabs SVO format.  Looking through the ZED SDK and through the mexZED interface file for matlab, this should be possible. If I run the following code I get no errors, but the svo file I specify is neither created nor saved. Any suggestions?

clc;
close all;
clear mex; clear functions; clear all;

mexZED('create');

InitParameters.camera_resolution = 2; %HD720
InitParameters.camera_fps = 60;
InitParameters.system_units = 2; %METER
InitParameters.depth_mode = 1; %PERFORMANCE
result = mexZED('open', InitParameters)

mexZED('enableRecording', {'TestSVOfile.svo'});
    
maxNframes=500;
for ff=1:maxNframes
    mexZED('record');
end

mexZED('disableRecording');
mexZED('close')
clear mex;

**Comment by P-yver** [comment]
Hi,
I have pushed a [Recording example](https://github.com/stereolabs/zed-matlab/blob/master/matlab/ZED_Recording.m) , the thing you miss is the call to the `grab` function, it is mandatory for decoding a new frame.
